version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmgt-postgres
    environment:
      POSTGRES_DB: taskmgt
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmgt -d taskmgt"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
